# Generated by Django 3.0.4 on 2020-04-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200412_1435'),
        ('article', '0004_auto_20200412_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user_collect',
            field=models.ManyToManyField(through='user.collect_blogs', to='user.User'),
        ),
    ]
