# Generated by Django 3.0.5 on 2020-09-17 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200720_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.CharField(blank=True, max_length=200, null=True)),
                ('list_class', models.CharField(blank=True, max_length=200, null=True)),
                ('single_id', models.CharField(blank=True, max_length=200, null=True)),
                ('single_class', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='article.Country')),
                ('universty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='article.University')),
            ],
        ),
    ]
