# Generated by Django 3.0.5 on 2020-09-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_add_source_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_source',
            old_name='single_class',
            new_name='body_class',
        ),
        migrations.RenameField(
            model_name='add_source',
            old_name='single_id',
            new_name='body_id',
        ),
        migrations.AddField(
            model_name='add_source',
            name='title_class',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='add_source',
            name='title_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
