# Generated by Django 3.0.5 on 2020-09-22 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20200922_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_source',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='article.Region'),
        ),
    ]
