# Generated by Django 3.0.5 on 2020-04-28 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200412_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_words', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='collect_blogs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_library', to='user.User', verbose_name='users'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_keywords',
            field=models.ManyToManyField(to='user.KeyWords'),
        ),
    ]
