# Generated by Django 3.0.5 on 2020-05-01 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200428_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word_1', models.CharField(max_length=50)),
                ('key_word_2', models.CharField(max_length=50)),
                ('key_word_3', models.CharField(max_length=50)),
                ('key_word_4', models.CharField(max_length=50)),
                ('key_word_5', models.CharField(max_length=50)),
                ('frequency', models.CharField(choices=[('M', 'Per Month'), ('W', 'Per Week'), ('D', 'Per Day'), ('N', 'Fastest')], default='M', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_reminder', to='user.User', verbose_name='users')),
            ],
        ),
    ]
