# Generated by Django 3.0.5 on 2020-05-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_email_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_keywords',
        ),
        migrations.DeleteModel(
            name='KeyWords',
        ),
    ]
