# Generated by Django 3.0.5 on 2020-07-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_user_collect'),
        ('user', '0007_auto_20200605_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_reminder',
            name='country',
            field=models.ManyToManyField(to='article.Country'),
        ),
        migrations.AddField(
            model_name='email_reminder',
            name='university',
            field=models.ManyToManyField(to='article.University'),
        ),
        migrations.RemoveField(
            model_name='email_reminder',
            name='key_word',
        ),
        migrations.AddField(
            model_name='email_reminder',
            name='key_word',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
