# Generated by Django 3.0.4 on 2020-08-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200720_0640'),
        ('user', '0008_auto_20200717_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_reminder',
            name='country',
        ),
        migrations.RemoveField(
            model_name='email_reminder',
            name='university',
        ),
        migrations.AddField(
            model_name='email_reminder',
            name='country_1',
            field=models.ManyToManyField(related_name='country_1', to='article.Country'),
        ),
        migrations.AddField(
            model_name='email_reminder',
            name='country_2',
            field=models.ManyToManyField(related_name='country_2', to='article.Country'),
        ),
        migrations.AddField(
            model_name='email_reminder',
            name='country_3',
            field=models.ManyToManyField(related_name='country_3', to='article.Country'),
        ),
        migrations.AddField(
            model_name='email_reminder',
            name='country_4',
            field=models.ManyToManyField(related_name='country_4', to='article.Country'),
        ),
        migrations.AddField(
            model_name='email_reminder',
            name='country_5',
            field=models.ManyToManyField(related_name='country_5', to='article.Country'),
        ),
        migrations.AddField(
            model_name='email_reminder',
            name='university_1',
            field=models.ManyToManyField(related_name='university_1', to='article.University'),
        ),
        migrations.AddField(
            model_name='email_reminder',
            name='university_2',
            field=models.ManyToManyField(related_name='university_2', to='article.University'),
        ),
        migrations.AddField(
            model_name='email_reminder',
            name='university_3',
            field=models.ManyToManyField(related_name='university_3', to='article.University'),
        ),
        migrations.AddField(
            model_name='email_reminder',
            name='university_4',
            field=models.ManyToManyField(related_name='university_4', to='article.University'),
        ),
        migrations.AddField(
            model_name='email_reminder',
            name='university_5',
            field=models.ManyToManyField(related_name='university_5', to='article.University'),
        ),
    ]
