# Generated by Django 3.0.4 on 2020-08-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200720_0640'),
        ('user', '0009_auto_20200818_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_reminder',
            name='country_1',
            field=models.ManyToManyField(blank=True, null=True, related_name='country_1', to='article.Country'),
        ),
    ]
