# Generated by Django 3.0.4 on 2020-08-19 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200720_0640'),
        ('user', '0011_auto_20200819_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_reminder',
            name='country_1',
        ),
        migrations.AddField(
            model_name='email_reminder',
            name='country_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_1', to='article.Country'),
        ),
        migrations.RemoveField(
            model_name='email_reminder',
            name='country_2',
        ),
        migrations.AddField(
            model_name='email_reminder',
            name='country_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_2', to='article.Country'),
        ),
        migrations.RemoveField(
            model_name='email_reminder',
            name='country_3',
        ),
        migrations.AddField(
            model_name='email_reminder',
            name='country_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_3', to='article.Country'),
        ),
        migrations.RemoveField(
            model_name='email_reminder',
            name='country_4',
        ),
        migrations.AddField(
            model_name='email_reminder',
            name='country_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_4', to='article.Country'),
        ),
        migrations.RemoveField(
            model_name='email_reminder',
            name='country_5',
        ),
        migrations.AddField(
            model_name='email_reminder',
            name='country_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_5', to='article.Country'),
        ),
        migrations.RemoveField(
            model_name='email_reminder',
            name='university_1',
        ),
        migrations.AddField(
            model_name='email_reminder',
            name='university_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university_1', to='article.University'),
        ),
        migrations.RemoveField(
            model_name='email_reminder',
            name='university_2',
        ),
        migrations.AddField(
            model_name='email_reminder',
            name='university_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university_2', to='article.University'),
        ),
        migrations.RemoveField(
            model_name='email_reminder',
            name='university_3',
        ),
        migrations.AddField(
            model_name='email_reminder',
            name='university_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university_3', to='article.University'),
        ),
        migrations.RemoveField(
            model_name='email_reminder',
            name='university_4',
        ),
        migrations.AddField(
            model_name='email_reminder',
            name='university_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university_4', to='article.University'),
        ),
        migrations.RemoveField(
            model_name='email_reminder',
            name='university_5',
        ),
        migrations.AddField(
            model_name='email_reminder',
            name='university_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university_5', to='article.University'),
        ),
    ]
