# Generated by Django 3.0.4 on 2020-08-19 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200720_0640'),
        ('user', '0012_auto_20200819_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_reminder',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discipline_choice', to='article.Discipline'),
        ),
    ]
