# Generated by Django 3.0.5 on 2020-08-27 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200825_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pay_time',
        ),
    ]
