# Generated by Django 3.0.5 on 2020-08-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_user_pay_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pay_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
