# Generated by Django 3.0.5 on 2020-08-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_user_pay_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expire',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
