# Generated by Django 3.0.5 on 2020-08-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='new_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
